# Generated by Django 5.2.3 on 2025-06-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
