# Generated by Django 5.2.3 on 2025-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='employee_id',
            new_name='employeeId',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='manager_id',
            new_name='teamId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='team_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee')], max_length=20),
        ),
    ]
