# Generated by Django 5.2.3 on 2025-06-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_employee_id_customuser_employeeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managerId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], max_length=20),
        ),
    ]
