# Generated by Django 5.2.3 on 2025-06-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeereport',
            old_name='highlights',
            new_name='description',
        ),
    ]
