# Generated by Django 5.2.3 on 2025-06-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_highlights_employeereport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.employeereport'),
        ),
    ]
