# Generated by Django 5.2.3 on 2025-06-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_feedback_acknowledged_feedback_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='report_id',
            field=models.CharField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
