# Generated by Django 5.2.3 on 2025-06-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employeereport_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeereport',
            name='report_id',
        ),
    ]
